<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Laporan Peminjaman</title>

    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
            color: #1e293b;
        }

        .header {
            margin-bottom: 20px;
        }

        .title {
            font-size: 20px;
            font-weight: bold;
            margin-bottom: 4px;
        }

        .subtitle {
            font-size: 12px;
            color: #64748b;
        }

        .info {
            margin-top: 10px;
            font-size: 11px;
        }

        .badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 6px;
            font-size: 10px;
        }

        .done { background: #dcfce7; color: #166534; }
        .returned { background: #dbeafe; color: #1e40af; }
        .pending { background: #fef3c7; color: #92400e; }
        .approved { background: #e0f2fe; color: #0369a1; }
        .rejected { background: #fee2e2; color: #991b1b; }
        .late { background: #fee2e2; color: #b91c1c; }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }

        thead {
            background: #f1f5f9;
        }

        th {
            text-align: left;
            padding: 8px;
            font-size: 11px;
            border-bottom: 1px solid #e2e8f0;
        }

        td {
            padding: 8px;
            border-bottom: 1px solid #f1f5f9;
        }

        tr:nth-child(even) {
            background: #fafafa;
        }

        .text-right {
            text-align: right;
        }

        .text-center {
            text-align: center;
        }

        .fine {
            color: #dc2626;
            font-weight: bold;
        }

        .footer {
            margin-top: 20px;
            font-size: 10px;
            color: #94a3b8;
            text-align: right;
        }
    </style>
</head>

<body>

    {{-- HEADER --}}
    <div class="header">
        <div class="title">Laporan Peminjaman Buku</div>
        <div class="subtitle">Sistem Perpustakaan LibraSys</div>

        <div class="info">
            Status Filter: <strong>{{ request('status') ?? 'Semua' }}</strong><br>
            Tanggal Export: {{ date('d M Y H:i') }}
        </div>
    </div>

    {{-- TABLE --}}
    <table>
        <thead>
            <tr>
                <th width="30">No</th>
                <th>User</th>
                <th>Book</th>
                <th width="80">Borrow</th>
                <th width="80">Return</th>
                <th width="90">Status</th>
                <th width="80" class="text-right">Fine</th>
            </tr>
        </thead>
        <tbody>
            @foreach($transactions as $key => $trx)
            <tr>
                <td class="text-center">{{ $key+1 }}</td>
                <td>{{ $trx->user->name }}</td>
                <td>{{ $trx->book->title }}</td>
                <td>{{ \Carbon\Carbon::parse($trx->borrow_date)->format('d M Y') }}</td>
                <td>{{ \Carbon\Carbon::parse($trx->return_date)->format('d M Y') }}</td>
                <td>
                    @php $status = $trx->status; @endphp

                    <span class="badge {{ $status }}">
                        {{ ucfirst($status) }}
                    </span>
                </td>
                <td class="text-right">
                    @if($trx->fine > 0)
                        <span class="fine">
                            Rp {{ number_format($trx->fine,0,',','.') }}
                        </span>
                    @else
                        -
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    {{-- FOOTER --}}
    <div class="footer">
        Generated by LibraSys • {{ date('Y') }}
    </div>

</body>
</html>